const routeNames = {
  signin: '/',
  signup: '/email-verification',
  authPin: '/auth-pin',
  authPinNewuser: '/auth-pin-new',
  authPinSetUp: '/auth-pin-set-up',
  forgotPassword: '/forgotPassword',
  createpassword: '/createpassword',
  home: '/app',
  dashboard: '/app/dashboard',
  instutitions: '/app/instutitions',
  viewInstitution: '/app/instutitions/view-institute',
  viewReportCategories: '/app/reports/community-task',
  addReportTasks: '/app/reports/add-task',
  surveyIndicator: '/app/reports/institutional-survey',
  surveyAddQuestion: '/app/reports/institutional-survey/add-question',
  surveyViewCategories: '/app/reports/institutional-survey/categories',
  surveyViewQuestion: '/app/reports/institutional-survey/questions',
  surveyViewQuestionSingle:
    '/app/reports/institutional-survey/questions-single',
  surveyViewIndividualCategories:
    '/app/reports/institutional-survey/category-single',
  surveyViewIndicatorMain: '/app/reports/institutional-survey/indicators',
  surveyViewIndicatorSingle:
    '/app/reports/institutional-survey/indicators-single',
  reportCategories: '/app/reports/categories',
  viewIndivualCategory: '/app/reports/categories/view',
  reportIndicator: '/app/reports/indicators',
  reportTaskPoser: '/app/reports/task-poser',
  viewIndividualReportTaskPoser: '/app/reports/task-poser/view',
  viewEditIndividualReportTaskPoser: '/app/reports/task-poser/view/edit',
  viewAllPendingTasks: '/app/reports/view-pending-task',
  viewPendingResponse: '/app/reports/view-pending-response',
  viewReviewedResponse: '/app/reports/view-reviewed-response',
  viewIndivualIndicator: '/app/reports/indicators/view',
  additionalComment: '/app/instutitions/view-institute/additional-comment',
  genericReport: '/app/instutitions/view-institute/generic-report',
  viewInstituteResponse: '/app/instutitions/view-institute/view-response',
  allInstitutions: '/app/instutitions/all-institutions',
  reports: '/app/reports',
  users: '/app/users',
  leaderboard: '/app/leaderboard',
  settings: '/app/settings',
  viewAdmin: '/app/settings/view-admin/:userId',
  rolesAndPermissions: '/app/settings/roles-and-permissions',
  validateKyc: '/app/users/validate-kyc/:userId',
  userProfile: '/app/users/profile/:userId',
  noWhere: '*',
}

export default routeNames
