const routeNames = {
  signin: "/",
  signup: "/signup",
  authPin: "/auth-pin",
  forgotPassword: "/forgotPassword",
  createpassword: "/createpassword",
  home: "/app",
  dashboard: "/app/dashboard",
  instutitions: "/app/instutitions",
  viewInstitution: "/app/instutitions/view-institute",
  additionalComment: "/app/instutitions/view-institute/additional-comment",
  genericReport: "/app/instutitions/view-institute/generic-report",
  viewInstituteResponse: "/app/instutitions/view-institute/view-response",
  allInstitutions: "/app/instutitions/all-institutions",
  reports: "/app/reports",
  users: "/app/users",
  leaderboard: "/app/leaderboard",
  settings: "/app/settings",
  viewAdmin: "/app/settings/view-admin",
  rolesAndPermissions: "/app/settings/roles-and-permissions",
  validateKyc:"/app/users/validate-kyc",
  userProfile: "/app/users/profile",
  noWhere: "*",
};

export default routeNames;
